-- 1 . Get all customers living in Berlin
-- 1b . Get all customers living in Berlin. Show them in alphabetical order by their firstname.
-- 2 . Get all customers with the firstname starting with letter "k".
-- 3. Get all customers with the lastname ending with an 'a' or a 'n'.
-- 4a. Get the current year and the year of the birthdates of all customers.
-- 4b. Get the firstname, the lastname and the age of all customers.
-- 4c. Get the firstname, the lastname and the age of all customers starting with the oldest ones.
-- 5. Get the firstname, the lastname and the age of all customers younger than 27 starting by
--      the youngest ones.
-- 6. Get all customers who are older than 27 and younger than 35.
-- 7. Get the oldest 5 clients who have a google account.
-- 8. Get all the customers who registered after 7pm.
-- 9. Get all lastnames and each lastname is only shown once
--   i.e. Tischler
-- 	  	  Tischler
--   	  Tischler
--  is not valid. Only one Tischler.
-- 10. How many customers live in Berlin?
-- 11. How many customers live in Berlin or in Leipzig?
-- 12. Get all customers who bought something
-- 13. Get all customers and if they ordered, their orders.
-- 14. Get all customers who have not ordered anything.
-- 15. Get all products and their product categories.